<a href="https://colab.research.google.com/github/Praveenraju10/15_days_workshop/blob/main/Day_3/Day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install requests --quiet
import pandas as pd
import numpy as np
import requests
import matplotlib.pyplot as plt


print('All libraries imported successfully')
print(f'pandas :{pd.__version__}')
print(f'requests:{requests.__version__}')

All libraries imported successfully
pandas :2.2.2
requests:2.32.4

In [4]:
df=pd.read_csv('/content/messy_sales_data.csv')
print(f'Raw data loaded :{df.shape[0]} rows, {df.shape[1]} columns')
df.head()

Raw data loaded :31 rows, 9 columns

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,05-01-2024,Mumbai,Anil Sharma
1,1002,Priya Nair,NaN,Electronics,1.0,15000,07-01-2024,Delhi,Sunita Rao
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,08-01-2024,Bangalore,Anil Sharma
3,1004,Sunita Patel,Monitor,Electronics,NaN,22000,10-01-2024,Chennai,Ravi Kumar
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,05-01-2024,Mumbai,Anil Sharma

In [5]:
#missing values
print(df.isnull().sum())

order_id         0
customer_name    2
product          1
category         1
quantity         3
unit_price       0
order_date       0
city             0
sales_rep        0
dtype: int64

In [6]:
#duplicates
print(df.duplicated().sum())

1

In [7]:
#unique values in text columns
print(df['category'].unique())
print(df['customer_name'].dropna().unique())
print(df['order_date'].unique()[:6])

['Electronics' 'Accessories' nan]
['Ramesh Kumar' 'Priya Nair' 'AMIT VERMA' 'Sunita Patel' 'kiran mehta'
 'Deepak Singh' 'Ananya Das' 'Vikram Iyer' 'Pooja Gupta' 'SURESH RAO'
 'Meera Joshi' 'Arjun Nair' 'Tanvi Mehta' 'Kiran Mehta' 'Rohit Verma'
 'Sneha Reddy' 'Gaurav Shukla' 'Nisha Kapoor' 'Ajay Tiwari' 'ANANYA DAS'
 'Preeti Saxena' 'Amit Bose' 'Rekha Nair' 'Harish Pillai' 'Sanjay Dubey'
 'Kavya Nambiar']
['05-01-2024' '07-01-2024' '08-01-2024' '10-01-2024' '12-01-2024'
 '13-01-2024']

In [8]:
#data types
print(df.dtypes)

order_id           int64
customer_name     object
product           object
category          object
quantity         float64
unit_price         int64
order_date        object
city              object
sales_rep         object
dtype: object

In [9]:
print(df['quantity'].duplicated().sum())
print(df['quantity'].isnull().sum())

21
3

In [10]:
#ETL

In [11]:
dfo=df.copy()
print(f'copy created:{dfo.shape}')

copy created:(31, 9)

In [12]:
#1. handle the missing values
print('Before fixing nulls:',df.isnull().sum().sum(),'total missing values')

dfo['customer_name'].fillna('unknown customer',inplace=True)
median_qty=dfo['quantity'].median()
dfo['quantity'].fillna(median_qty,inplace=True)
print(f'Filled missing quality with median:{median_qty}')

dfo['category'].fillna('uncategorized',inplace=True)

print('After fixing nulls:',dfo.isnull().sum().sum(),'total missing values')

Before fixing nulls: 7 total missing values
Filled missing quality with median:2.0
After fixing nulls: 1 total missing values

/tmp/ipykernel_7695/760426430.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dfo['customer_name'].fillna('unknown customer',inplace=True)
/tmp/ipykernel_7695/760426430.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dfo['quantity'].fillna(median_qty,inplace=True)
/tmp/ipykernel_7695/760426430.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dfo['category'].fillna('uncategorized',inplace=True)

In [13]:
dfo

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,05-01-2024,Mumbai,Anil Sharma
1,1002,Priya Nair,NaN,Electronics,1.0,15000,07-01-2024,Delhi,Sunita Rao
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,08-01-2024,Bangalore,Anil Sharma
3,1004,Sunita Patel,Monitor,Electronics,2.0,22000,10-01-2024,Chennai,Ravi Kumar
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,05-01-2024,Mumbai,Anil Sharma
5,1006,kiran mehta,Mouse,Accessories,10.0,800,07-01-2024,Pune,Sunita Rao
6,1007,Deepak Singh,Headphones,Electronics,2.0,3500,12-01-2024,Hyderabad,Ravi Kumar
7,1008,unknown customer,Webcam,Accessories,1.0,2500,13-01-2024,Mumbai,Anil Sharma
8,1009,Ananya Das,Laptop,Electronics,1.0,45000,15-01-2024,Kolkata,Sunita Rao
9,1010,Vikram Iyer,Keyboard,Accessories,5.0,1200,15-01-2024,Chennai,Ravi Kumar
10,1011,Pooja Gupta,Monitor,Electronics,2.0,22000,18-01-2024,Delhi,Anil Sharma
11,1012,SURESH RAO,USB Hub,Accessories,8.0,600,20-01-2024,Bangalore,Sunita Rao
12,1013,Meera Joshi,Laptop,Electronics,2.0,45000,22-01-2024,Pune,Ravi Kumar
13,1014,Arjun Nair,Headphones,Electronics,3.0,3500,21-01-2024,Kochi,Anil Sharma
14,1015,Tanvi Mehta,Webcam,Accessories,2.0,2500,25-01-2024,Surat,Sunita Rao
15,1016,Kiran Mehta,Mouse,Accessories,10.0,800,07-01-2024,Pune,Sunita Rao
16,1017,Deepak Singh,Keyboard,Accessories,5.0,1200,28-01-2024,Hyderabad,Ravi Kumar
17,1018,Rohit Verma,Monitor,Electronics,1.0,22000,30-01-2024,Delhi,Anil Sharma
18,1019,Sneha Reddy,Laptop,Electronics,1.0,45000,01-02-2024,Hyderabad,Ravi Kumar
19,1020,Gaurav Shukla,USB Hub,Accessories,15.0,600,03-02-2024,Lucknow,Sunita Rao
20,1021,Nisha Kapoor,Headphones,Electronics,2.0,3500,05-02-2024,Chandigarh,Anil Sharma
21,1022,Ajay Tiwari,Webcam,Accessories,3.0,2500,07-02-2024,Bhopal,Ravi Kumar
22,1023,ANANYA DAS,Laptop,Electronics,1.0,45000,15-01-2024,Kolkata,Sunita Rao
23,1024,Preeti Saxena,Keyboard,Electronics,4.0,1200,10-02-2024,Kanpur,Anil Sharma
24,1025,Amit Bose,Mouse,Accessories,6.0,800,12-02-2024,Kolkata,Sunita Rao
25,1026,unknown customer,Headphones,Electronics,1.0,3500,14-02-2024,Mumbai,Ravi Kumar
26,1027,Rekha Nair,Monitor,uncategorized,2.0,22000,15-02-2024,Kochi,Anil Sharma
27,1028,Harish Pillai,Laptop,Electronics,3.0,45000,18-02-2024,Thiruvananthapuram,Ravi Kumar
28,1029,Sanjay Dubey,USB Hub,Accessories,10.0,600,20-02-2024,Allahabad,Sunita Rao
29,1030,Kavya Nambiar,Webcam,Accessories,2.0,2500,22-02-2024,Thrissur,Anil Sharma
30,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,05-01-2024,Mumbai,Anil Sharma

In [14]:
print(f'Before deduplication:{len(dfo)}')
print(f'Duplicate rows:{dfo.duplicated().sum()}')
print('\n Duplicate rows')
print(dfo[dfo.duplicated(keep=False)][['order_id','customer_name','product','order_date']].head(6))
dfo.drop_duplicates(inplace=True)
print(f'\nAfter deduplication:{len(dfo)} rows')
print(f'row reomved:{len(df)- len(dfo)}')

Before deduplication:31
Duplicate rows:1

 Duplicate rows
    order_id customer_name product  order_date
4       1005  Ramesh Kumar  Laptop  05-01-2024
30      1005  Ramesh Kumar  Laptop  05-01-2024

After deduplication:30 rows
row reomved:1

In [15]:

dfo['product'].fillna('unknown product',inplace=True)
print(dfo['product'])
print(dfo['product'].isnull().sum())

0              Laptop
1     unknown product
2            Keyboard
3             Monitor
4              Laptop
5               Mouse
6          Headphones
7              Webcam
8              Laptop
9            Keyboard
10            Monitor
11            USB Hub
12             Laptop
13         Headphones
14             Webcam
15              Mouse
16           Keyboard
17            Monitor
18             Laptop
19            USB Hub
20         Headphones
21             Webcam
22             Laptop
23           Keyboard
24              Mouse
25         Headphones
26            Monitor
27             Laptop
28            USB Hub
29             Webcam
Name: product, dtype: object
0

/tmp/ipykernel_7695/2174091699.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dfo['product'].fillna('unknown product',inplace=True)

In [16]:
dfo

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,05-01-2024,Mumbai,Anil Sharma
1,1002,Priya Nair,unknown product,Electronics,1.0,15000,07-01-2024,Delhi,Sunita Rao
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,08-01-2024,Bangalore,Anil Sharma
3,1004,Sunita Patel,Monitor,Electronics,2.0,22000,10-01-2024,Chennai,Ravi Kumar
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,05-01-2024,Mumbai,Anil Sharma
5,1006,kiran mehta,Mouse,Accessories,10.0,800,07-01-2024,Pune,Sunita Rao
6,1007,Deepak Singh,Headphones,Electronics,2.0,3500,12-01-2024,Hyderabad,Ravi Kumar
7,1008,unknown customer,Webcam,Accessories,1.0,2500,13-01-2024,Mumbai,Anil Sharma
8,1009,Ananya Das,Laptop,Electronics,1.0,45000,15-01-2024,Kolkata,Sunita Rao
9,1010,Vikram Iyer,Keyboard,Accessories,5.0,1200,15-01-2024,Chennai,Ravi Kumar
10,1011,Pooja Gupta,Monitor,Electronics,2.0,22000,18-01-2024,Delhi,Anil Sharma
11,1012,SURESH RAO,USB Hub,Accessories,8.0,600,20-01-2024,Bangalore,Sunita Rao
12,1013,Meera Joshi,Laptop,Electronics,2.0,45000,22-01-2024,Pune,Ravi Kumar
13,1014,Arjun Nair,Headphones,Electronics,3.0,3500,21-01-2024,Kochi,Anil Sharma
14,1015,Tanvi Mehta,Webcam,Accessories,2.0,2500,25-01-2024,Surat,Sunita Rao
15,1016,Kiran Mehta,Mouse,Accessories,10.0,800,07-01-2024,Pune,Sunita Rao
16,1017,Deepak Singh,Keyboard,Accessories,5.0,1200,28-01-2024,Hyderabad,Ravi Kumar
17,1018,Rohit Verma,Monitor,Electronics,1.0,22000,30-01-2024,Delhi,Anil Sharma
18,1019,Sneha Reddy,Laptop,Electronics,1.0,45000,01-02-2024,Hyderabad,Ravi Kumar
19,1020,Gaurav Shukla,USB Hub,Accessories,15.0,600,03-02-2024,Lucknow,Sunita Rao
20,1021,Nisha Kapoor,Headphones,Electronics,2.0,3500,05-02-2024,Chandigarh,Anil Sharma
21,1022,Ajay Tiwari,Webcam,Accessories,3.0,2500,07-02-2024,Bhopal,Ravi Kumar
22,1023,ANANYA DAS,Laptop,Electronics,1.0,45000,15-01-2024,Kolkata,Sunita Rao
23,1024,Preeti Saxena,Keyboard,Electronics,4.0,1200,10-02-2024,Kanpur,Anil Sharma
24,1025,Amit Bose,Mouse,Accessories,6.0,800,12-02-2024,Kolkata,Sunita Rao
25,1026,unknown customer,Headphones,Electronics,1.0,3500,14-02-2024,Mumbai,Ravi Kumar
26,1027,Rekha Nair,Monitor,uncategorized,2.0,22000,15-02-2024,Kochi,Anil Sharma
27,1028,Harish Pillai,Laptop,Electronics,3.0,45000,18-02-2024,Thiruvananthapuram,Ravi Kumar
28,1029,Sanjay Dubey,USB Hub,Accessories,10.0,600,20-02-2024,Allahabad,Sunita Rao
29,1030,Kavya Nambiar,Webcam,Accessories,2.0,2500,22-02-2024,Thrissur,Anil Sharma

In [17]:
dfo['order_date']=pd.to_datetime(dfo['order_date'],dayfirst=False,errors='coerce')
dfo['order_date'].unique()

<DatetimeArray>
['2024-05-01 00:00:00', '2024-07-01 00:00:00', '2024-08-01 00:00:00',
 '2024-10-01 00:00:00', '2024-12-01 00:00:00',                 'NaT',
 '2024-01-02 00:00:00', '2024-03-02 00:00:00', '2024-05-02 00:00:00',
 '2024-07-02 00:00:00', '2024-10-02 00:00:00', '2024-12-02 00:00:00']
Length: 12, dtype: datetime64[ns]

In [18]:
dfo['year']=dfo['order_date'].dt.year
dfo['month']=dfo['order_date'].dt.month
dfo['day']=dfo['order_date'].dt.day

In [19]:
dfo['customer_name'].unique()[:10]

array(['Ramesh Kumar', 'Priya Nair', 'AMIT VERMA', 'Sunita Patel',
       'kiran mehta', 'Deepak Singh', 'unknown customer', 'Ananya Das',
       'Vikram Iyer', 'Pooja Gupta'], dtype=object)

In [20]:
dfo['customer_name']=(dfo['customer_name'].str.strip().str.title())
dfo['customer_name'].unique()[:10]

array(['Ramesh Kumar', 'Priya Nair', 'Amit Verma', 'Sunita Patel',
       'Kiran Mehta', 'Deepak Singh', 'Unknown Customer', 'Ananya Das',
       'Vikram Iyer', 'Pooja Gupta'], dtype=object)

In [21]:
mask=(dfo['product']=='keybord') &(dfo['category']=='Electronics')
dfo.loc[mask,'category']='Accessaries'
print(dfo.loc[mask, 'category'])

Series([], Name: category, dtype: object)

In [22]:
dfo['quantity']=pd.to_numeric(dfo['quantity'],errors='coerce')
dfo['unit_price']=pd.to_numeric(dfo['unit_price'],errors='coerce')
dfo['Revenue']=df['unit_price']*dfo['quantity']
print(dfo[['customer_name','product','quantity','unit_price','Revenue']].head(5))

  customer_name          product  quantity  unit_price  Revenue
0  Ramesh Kumar           Laptop       2.0       45000  90000.0
1    Priya Nair  unknown product       1.0       15000  15000.0
2    Amit Verma         Keyboard       3.0        1200   3600.0
3  Sunita Patel          Monitor       2.0       22000  44000.0
4  Ramesh Kumar           Laptop       2.0       45000  90000.0

In [23]:
total=dfo['Revenue'].sum()
print(total)

818000.0

In [25]:
print(f'original rows: {len(df)}')
print(f'cleaned rows : {len(dfo)}')
print(f'rows removed : {len(df)-len(dfo)}')
print(f'Missing values: {dfo.isnull().sum().sum()}')
print(f'Duplicate rows: {dfo.duplicated().sum()}')
print(f'Date nulls : {dfo['order_date'].isnull().sum()}')
print(f'Revenue null: {dfo['Revenue'].isnull().sum()}')

original rows: 31
cleaned rows : 30
rows removed : 1
Missing values: 64
Duplicate rows: 0
Date nulls : 16
Revenue null: 0

In [26]:
dfo

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep,year,month,day,Revenue
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-05-01,Mumbai,Anil Sharma,2024.0,5.0,1.0,90000.0
1,1002,Priya Nair,unknown product,Electronics,1.0,15000,2024-07-01,Delhi,Sunita Rao,2024.0,7.0,1.0,15000.0
2,1003,Amit Verma,Keyboard,Accessories,3.0,1200,2024-08-01,Bangalore,Anil Sharma,2024.0,8.0,1.0,3600.0
3,1004,Sunita Patel,Monitor,Electronics,2.0,22000,2024-10-01,Chennai,Ravi Kumar,2024.0,10.0,1.0,44000.0
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-05-01,Mumbai,Anil Sharma,2024.0,5.0,1.0,90000.0
5,1006,Kiran Mehta,Mouse,Accessories,10.0,800,2024-07-01,Pune,Sunita Rao,2024.0,7.0,1.0,8000.0
6,1007,Deepak Singh,Headphones,Electronics,2.0,3500,2024-12-01,Hyderabad,Ravi Kumar,2024.0,12.0,1.0,7000.0
7,1008,Unknown Customer,Webcam,Accessories,1.0,2500,NaT,Mumbai,Anil Sharma,NaN,NaN,NaN,2500.0
8,1009,Ananya Das,Laptop,Electronics,1.0,45000,NaT,Kolkata,Sunita Rao,NaN,NaN,NaN,45000.0
9,1010,Vikram Iyer,Keyboard,Accessories,5.0,1200,NaT,Chennai,Ravi Kumar,NaN,NaN,NaN,6000.0
10,1011,Pooja Gupta,Monitor,Electronics,2.0,22000,NaT,Delhi,Anil Sharma,NaN,NaN,NaN,44000.0
11,1012,Suresh Rao,USB Hub,Accessories,8.0,600,NaT,Bangalore,Sunita Rao,NaN,NaN,NaN,4800.0
12,1013,Meera Joshi,Laptop,Electronics,2.0,45000,NaT,Pune,Ravi Kumar,NaN,NaN,NaN,90000.0
13,1014,Arjun Nair,Headphones,Electronics,3.0,3500,NaT,Kochi,Anil Sharma,NaN,NaN,NaN,10500.0
14,1015,Tanvi Mehta,Webcam,Accessories,2.0,2500,NaT,Surat,Sunita Rao,NaN,NaN,NaN,5000.0
15,1016,Kiran Mehta,Mouse,Accessories,10.0,800,2024-07-01,Pune,Sunita Rao,2024.0,7.0,1.0,8000.0
16,1017,Deepak Singh,Keyboard,Accessories,5.0,1200,NaT,Hyderabad,Ravi Kumar,NaN,NaN,NaN,6000.0
17,1018,Rohit Verma,Monitor,Electronics,1.0,22000,NaT,Delhi,Anil Sharma,NaN,NaN,NaN,22000.0
18,1019,Sneha Reddy,Laptop,Electronics,1.0,45000,2024-01-02,Hyderabad,Ravi Kumar,2024.0,1.0,2.0,45000.0
19,1020,Gaurav Shukla,USB Hub,Accessories,15.0,600,2024-03-02,Lucknow,Sunita Rao,2024.0,3.0,2.0,9000.0
20,1021,Nisha Kapoor,Headphones,Electronics,2.0,3500,2024-05-02,Chandigarh,Anil Sharma,2024.0,5.0,2.0,7000.0
21,1022,Ajay Tiwari,Webcam,Accessories,3.0,2500,2024-07-02,Bhopal,Ravi Kumar,2024.0,7.0,2.0,7500.0
22,1023,Ananya Das,Laptop,Electronics,1.0,45000,NaT,Kolkata,Sunita Rao,NaN,NaN,NaN,45000.0
23,1024,Preeti Saxena,Keyboard,Electronics,4.0,1200,2024-10-02,Kanpur,Anil Sharma,2024.0,10.0,2.0,4800.0
24,1025,Amit Bose,Mouse,Accessories,6.0,800,2024-12-02,Kolkata,Sunita Rao,2024.0,12.0,2.0,4800.0
25,1026,Unknown Customer,Headphones,Electronics,1.0,3500,NaT,Mumbai,Ravi Kumar,NaN,NaN,NaN,3500.0
26,1027,Rekha Nair,Monitor,uncategorized,2.0,22000,NaT,Kochi,Anil Sharma,NaN,NaN,NaN,44000.0
27,1028,Harish Pillai,Laptop,Electronics,3.0,45000,NaT,Thiruvananthapuram,Ravi Kumar,NaN,NaN,NaN,135000.0
28,1029,Sanjay Dubey,USB Hub,Accessories,10.0,600,NaT,Allahabad,Sunita Rao,NaN,NaN,NaN,6000.0
29,1030,Kavya Nambiar,Webcam,Accessories,2.0,2500,NaT,Thrissur,Anil Sharma,NaN,NaN,NaN,5000.0