<a href="https://colab.research.google.com/github/Praveenraju10/15_days_workshop/blob/main/Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd

In [10]:
print("Libraries imported successfully")

Libraries imported successfully

In [11]:
df=pd.read_csv('student_performance.csv')

In [13]:
print(df.tail())

    student_id            name  age  gender        department  semester  \
25        1026      Rekha Nair   20  Female       Electronics         2
26        1027   Gaurav Shukla   21    Male  Computer Science         2
27        1028   Sunita Pillai   19  Female             Civil         2
28        1029      Nitin Jain   20    Male        Mechanical         2
29        1030  Akanksha Yadav   19  Female  Computer Science         2

    math_score  science_score  english_score  programming_score  \
25          72             77             73                 63
26          84             79             75                 87
27          60             65             68                 39
28          75             76             70                 50
29          91             93             87                 94

    attendance_percentage                city  admission_year
25                     82               Kochi            2023
26                     87             Lucknow            2023
27                     73  Thiruvananthapuram            2023
28                     84              Indore            2023
29                     95                Agra            2023

In [14]:
print("shape of dataset:",df.shape)

shape of dataset: (30, 13)

In [15]:
print("number of students:",df.shape[0])

number of students: 30

In [16]:
print("number of columns:",df.shape[1])

number of columns: 13

In [21]:
print("colomns in dataset:",df.columns.tolist())

colomns in dataset: ['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [19]:
print("datatypes:",df.dtypes)

datatypes: student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [22]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [24]:
print("missing values in each column:",df.isnull().sum())

missing values in each column: student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [25]:
print("total missing :",df.isnull().sum().sum())

total missing : 0

In [30]:
print("students name:")
print(df['name'])

students name:
0       Aarav Sharma
1        Priya Patel
2        Rohit Verma
3        Sneha Reddy
4         Arjun Nair
5        Meera Joshi
6        Kiran Kumar
7        Divya Singh
8       Rahul Mishra
9         Ananya Das
10       Vikram Iyer
11       Pooja Gupta
12        Suresh Rao
13     Kavya Nambiar
14       Ajay Tiwari
15      Ritu Agarwal
16      Manoj Pandey
17    Swati Kulkarni
18    Deepak Chauhan
19      Nisha Kapoor
20     Harish Pillai
21       Tanvi Mehta
22      Sanjay Dubey
23     Preeti Saxena
24         Amit Bose
25        Rekha Nair
26     Gaurav Shukla
27     Sunita Pillai
28        Nitin Jain
29    Akanksha Yadav
Name: name, dtype: object

In [32]:
print("department in this dataset:",df['department'].unique())

department in this dataset: ['Computer Science' 'Electronics' 'Mechanical' 'Civil']

In [33]:
print("how many students per department:",df['department'].value_counts())

how many students per department: department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [38]:
cs_students=df[df['department']=='Computer Science']
print("number of students in cs:",len(cs_students))

number of students in cs: 13

In [41]:
print("cs students:")
print(cs_students[['name','department','math_score']])

cs students:
              name        department  math_score
0     Aarav Sharma  Computer Science          85
1      Priya Patel  Computer Science          76
4       Arjun Nair  Computer Science          92
7      Divya Singh  Computer Science          88
9       Ananya Das  Computer Science          95
12      Suresh Rao  Computer Science          83
14     Ajay Tiwari  Computer Science          71
17  Swati Kulkarni  Computer Science          90
19    Nisha Kapoor  Computer Science          79
21     Tanvi Mehta  Computer Science          93
24       Amit Bose  Computer Science          86
26   Gaurav Shukla  Computer Science          84
29  Akanksha Yadav  Computer Science          91

In [50]:
cs_above = df[(df['department'] == 'Computer Science') & (df['attendance_percentage'] > 90)]
cs_above

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [86]:
df['total_score']=df[['english_score','math_score','programming_score','science_score']].sum(axis=1)
top_performers_index=df['top_performer'].sort_values(ascending=False).index

print(df.loc[top_performers_index,['name','department']])

              name        department
9       Ananya Das  Computer Science
21     Tanvi Mehta  Computer Science
29  Akanksha Yadav  Computer Science
4       Arjun Nair  Computer Science
7      Divya Singh  Computer Science
17  Swati Kulkarni  Computer Science
24       Amit Bose  Computer Science
12      Suresh Rao  Computer Science
19    Nisha Kapoor  Computer Science
0     Aarav Sharma  Computer Science
26   Gaurav Shukla  Computer Science
15    Ritu Agarwal       Electronics
1      Priya Patel  Computer Science
10     Vikram Iyer       Electronics
23   Preeti Saxena        Mechanical
25      Rekha Nair       Electronics
13   Kavya Nambiar        Mechanical
14     Ajay Tiwari  Computer Science
3      Sneha Reddy        Mechanical
28      Nitin Jain        Mechanical
11     Pooja Gupta             Civil
20   Harish Pillai       Electronics
2      Rohit Verma       Electronics
18  Deepak Chauhan        Mechanical
6      Kiran Kumar             Civil
5      Meera Joshi       Electronics
8     Rahul Mishra        Mechanical
27   Sunita Pillai             Civil
22    Sanjay Dubey             Civil
16    Manoj Pandey             Civil

In [100]:
dept_avg=df.groupby('department')['total_score'].mean().round(2)
print(dept_avg.sort_values(ascending=False))

department
Computer Science    340.15
Electronics         277.50
Mechanical          267.33
Civil               235.80
Name: total_score, dtype: float64